development:
  adapter: postgresql
  database: quiz_development
  pool: 5
  timeout: 5000


test: &test
  adapter: postgresql
  database: quiz_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: quiz_production
  pool: 5
  timeout: 5000

cucumber:
  <<: *test
